version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: ballog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3306:3306"      # EC2 밖에서 접속하려면 열기
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ballog-network


  spring-boot-app:
    container_name: ballog-server
    restart: on-failure
    build: .
    image: chaeyeon01/ballog-server:latest
    ports:
      - "8082:8082"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:+IgnoreUnrecognizedVMOptions -XX:-UseContainerCpuShares -XX:-UseContainerCpuQuota -XX:-UseCGroupMemoryLimitForHeap"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ballog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      S3ACCESSKEY: ${S3ACCESSKEY}
      S3SECRETKEY: ${S3SECRETKEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAKAO_ADMIN_KEY: ${KAKAO_ADMIN_KEY}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_NAME: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_NAME}
      SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_AUTHORIZATION_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_AUTHORIZATION_URI}
      SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_TOKEN_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_TOKEN_URI}
      SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_INFO_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_INFO_URI}
      SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_ID: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_SECRET: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_REDIRECT_URI: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_REDIRECT_URI}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_AUTHORIZATION_GRANT_TYPE: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_AUTHORIZATION_GRANT_TYPE}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_NAME: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_APPLE_CLIENT_NAME}
      SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_AUTHORIZATION_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_AUTHORIZATION_URI}
      SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_TOKEN_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_TOKEN_URI}
      SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_PUBLICKEY_URL: ${SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_PUBLICKEY_URL}
      SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_USER_INFO_URI: ${SPRING_SECURITY_OAUTH2_PROVIDER_APPLE_USER_INFO_URI}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_LOGIN_KEY: ${APPLE_LOGIN_KEY}
      APPLE_KEY_PATH: ${APPLE_KEY_PATH}
      DEFAULT_IMAGE: ${DEFAULT_IMAGE}
      FRONTED_ELASTIC: ${FRONTED_ELASTIC}
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
      TZ: Asia/Seoul
    depends_on:
      - db
    networks:
      - ballog-network

  nginx:
    container_name: ballog-nginx
    image: nginx:1.24
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../data/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - spring-boot-app
    networks:
      - ballog-network
volumes:
  mysql-data:

networks:
  ballog-network:
    driver: bridge
